# GoReleaser configuration for cio
# https://goreleaser.com

version: 2

before:
  hooks:
    # Tidy dependencies
    - go mod tidy

builds:
  - id: cio
    main: ./cmd/cio
    binary: cio
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: cio
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - RELEASE.md
      - FUSE.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: thieso2
    name: cio
  prerelease: auto
  mode: replace
  draft: false

# Homebrew tap (optional - uncomment if you want to publish to Homebrew)
# brews:
#   - repository:
#       owner: thieso2
#       name: homebrew-tap
#     directory: Formula
#     homepage: https://github.com/thieso2/cio
#     description: "Fast Go CLI for Google Cloud Storage and BigQuery"
#     license: MIT
#     test: |
#       system "#{bin}/cio", "version"
